# Do not commit real secrets. This file is for illustration only.
# Put any secret keys in src/config/secrets.yaml (ignored by .gitignore).
#
# Example:
# providers:
#   openai_api_key: "sk-..."
#   slack_token: "xoxb-..."
